[build]
  base = "FE"
  publish = "FE/dist"
  command = "cd FE && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/deletion"
  to = "/deletion.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
