[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/deletion"
  to = "/deletion.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
